# Generated by Django 6.0 on 2026-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
