# Generated by Django 6.0 on 2026-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert_ai_explanation_alert_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('expense', 'Expense'), ('purchase', 'Purchase'), ('note', 'General Note')], max_length=20)),
                ('amount', models.FloatField(blank=True, help_text='Amount involved (if applicable)', null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
